### ISSUE TITLE
Wrong interface

### ISSUE THREAD

**Issue by dianaruthroy** [dneise/workflow_showcase#1]
Hey there! nice work!
But I think you made a mistake. The interface is wrong.

**Comment by dneise** [comment]
Hey Diana! Thanks for opening this issue. 

But I think you are mistaken. The interface follows [the design document](https://github.com/dneise/workflow_showcase/blob/main/README.md#purpose).

It says:
> ACS Component, which can store “a_number“ and publish it as an attribute.

And I think the interface follows quite verbally:
https://github.com/dneise/workflow_showcase/blob/fc08744425980285dab4f5e12ed737b77e57a6f8/example/idl/example.midl#L15-L17

**Comment by dianaruthroy** [comment]
Oh I see .. the document is easy to misunderstand. (I have to fix that soon)

In the meantime, please look at the [detailed design part](https://github.com/dneise/workflow_showcase#detailed-design)

**Comment by dneise** [comment]
Oh right! Now I understand. 

Thanks for pointing that out. I'll fix it right away.
